env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - prettier
rules: 
  "prettier/prettier": "error"  
