name: Run upstream tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: make update-tests
      - run: make test

